spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tech_platform?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: ilxw
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 50
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800

rocketmq:
  name-server: 127.0.0.1:9876
  topic: sms-common-topic
  producer:
      group: platform-sms-server-group